"""Tests for the web backend clip service.

Includes mock-based unit tests for window calculation, naming, and URL
formatting, plus an integration test that generates a real tiny video with
ffmpeg and verifies clip extraction.
"""

import os
import subprocess
import tempfile
import unittest
from unittest.mock import patch

from web.backend.services import clip_service


class TestClipServiceUnit(unittest.TestCase):
    """Mock-based tests for generate_clips logic."""

    @patch("web.backend.services.clip_service._extract_clip")
    def test_clip_naming_and_url(self, mock_extract):
        """Files are named serve-01.mp4, serve-02.mp4 with matching url_path."""
        serves = [
            {"contact_time_sec": 10.0},
            {"contact_time_sec": 25.5},
        ]
        result = clip_service.generate_clips("/tmp/video.mp4", serves)

        self.assertEqual(len(result), 2)
        self.assertEqual(result[0]["filename"], "serve-01.mp4")
        self.assertEqual(result[0]["url_path"], "/clips/serve-01.mp4")
        self.assertEqual(result[1]["filename"], "serve-02.mp4")
        self.assertEqual(result[1]["url_path"], "/clips/serve-02.mp4")

    @patch("web.backend.services.clip_service._extract_clip")
    def test_window_calculation(self, mock_extract):
        """Clip window is max(contact - 2.25, 0) to contact + 1.75."""
        serves = [
            {"contact_time_sec": 10.0},
            {"contact_time_sec": 1.0},
        ]
        clip_service.generate_clips("/tmp/video.mp4", serves)

        calls = mock_extract.call_args_list
        # Serve 1: 10.0 -> start 7.75, end 11.75
        self.assertEqual(calls[0][0][1], 7.75)
        self.assertEqual(calls[0][0][2], 11.75)
        # Serve 2: 1.0 -> start 0.0 (clamped), end 2.75
        self.assertEqual(calls[1][0][1], 0.0)
        self.assertEqual(calls[1][0][2], 2.75)

    @patch("web.backend.services.clip_service._extract_clip")
    def test_duration_field(self, mock_extract):
        """Duration equals end - start."""
        serves = [{"contact_time_sec": 5.0}]
        result = clip_service.generate_clips("/tmp/video.mp4", serves)
        # start = 2.75, end = 6.75, duration = 4.0
        self.assertEqual(result[0]["duration"], 4.0)

    @patch("web.backend.services.clip_service._extract_clip")
    def test_serve_index_field(self, mock_extract):
        """serve_index is 1-indexed."""
        serves = [{"contact_time_sec": 1.0}, {"contact_time_sec": 2.0}]
        result = clip_service.generate_clips("/tmp/video.mp4", serves)
        self.assertEqual(result[0]["serve_index"], 1)
        self.assertEqual(result[1]["serve_index"], 2)

    @patch("web.backend.services.clip_service._extract_clip")
    def test_empty_selected_serves(self, mock_extract):
        """Empty input returns empty metadata list, no ffmpeg calls."""
        result = clip_service.generate_clips("/tmp/video.mp4", [])
        self.assertEqual(result, [])
        mock_extract.assert_not_called()

    @patch("web.backend.services.clip_service._extract_clip")
    def test_contact_time_passed_through(self, mock_extract):
        """contact_time_sec is preserved in metadata."""
        serves = [{"contact_time_sec": 42.5}]
        result = clip_service.generate_clips("/tmp/video.mp4", serves)
        self.assertEqual(result[0]["contact_time_sec"], 42.5)


class TestClipServiceIntegration(unittest.TestCase):
    """Integration test with a real tiny video generated by ffmpeg."""

    def setUp(self):
        self.temp_dir = tempfile.mkdtemp(prefix="serve_analyzer_test_")
        self.video_path = os.path.join(self.temp_dir, "test_video.mp4")
        # Generate a 5-second 640x480 test video at 30 fps
        subprocess.run(
            [
                "ffmpeg",
                "-f",
                "lavfi",
                "-i",
                "testsrc=duration=5:size=640x480:rate=30",
                "-c:v",
                "libx264",
                "-pix_fmt",
                "yuv420p",
                "-y",
                self.video_path,
            ],
            capture_output=True,
            check=True,
        )
        os.environ["SERVE_ANALYZER_TEMP"] = self.temp_dir

    def tearDown(self):
        if os.path.isfile(self.video_path):
            os.remove(self.video_path)
        if os.path.isdir(self.temp_dir):
            import shutil

            shutil.rmtree(self.temp_dir)
        os.environ.pop("SERVE_ANALYZER_TEMP", None)

    def test_generate_clips_creates_mp4_files(self):
        """Clips are extracted, scaled, and written as valid MP4 files."""
        serves = [
            {"contact_time_sec": 2.0},
            {"contact_time_sec": 4.0},
        ]
        result = clip_service.generate_clips(self.video_path, serves)

        self.assertEqual(len(result), 2)
        for meta in result:
            path = os.path.join(self.temp_dir, "clips", meta["filename"])
            self.assertTrue(
                os.path.isfile(path),
                f"Expected clip file {path} to exist",
            )
            self.assertGreater(
                os.path.getsize(path),
                0,
                f"Clip file {path} should not be empty",
            )

    def test_cleanup_clips_removes_files(self):
        """cleanup_clips removes all files from the clips directory."""
        serves = [{"contact_time_sec": 2.0}]
        clip_service.generate_clips(self.video_path, serves)
        clip_service.cleanup_clips()
        clips_dir = os.path.join(self.temp_dir, "clips")
        if os.path.isdir(clips_dir):
            self.assertEqual(os.listdir(clips_dir), [])


if __name__ == "__main__":
    unittest.main()
